import type { CostType } from "./detectCostType";

export type WorkTypeDefaultCostType = {
  costType: CostType;
  needsReview?: boolean;
};

function buildCostTypeMap(workTypes: readonly string[], costType: CostType, needsReview = false) {
  return Object.fromEntries(workTypes.map((workType) => [workType, { costType, needsReview }])) as Record<
    string,
    WorkTypeDefaultCostType
  >;
}

const LAB_WORK_TYPES = [
  "Site management staff",
  "Protection of existing works",
  "Survey / setout",
  "Closeout / handover",
  "Demolition",
  "Soft strip",
  "Salvage / make-good",
  "Existing services disconnection",
  "Existing structure alteration",
  "Remediation / contamination",
  "Site preparation",
  "Bulk earthworks",
  "Cut / fill / compaction",
  "Excavation / trenching",
  "Imported fill / engineered fill",
  "Retaining structures",
  "Stormwater siteworks",
  "Pavement base / subbase",
  "Concrete paving",
  "Unit paving",
  "Kerbs / channels / ancillaries",
  "External stairs / ramps",
  "Fences / gates / barriers",
  "Landscaping",
  "Irrigation",
  "External furniture / signage",
  "Piling",
  "Ground improvement",
  "Excavation to foundations",
  "Blinding",
  "Footings",
  "Foundation walls / beams",
  "Slab on grade",
  "Suspended slabs",
  "Reinforcement",
  "Post-tensioning",
  "Formwork",
  "In-situ concrete",
  "Precast concrete",
  "Concrete finishes",
  "Concrete remediation / repair",
  "Structural steel",
  "Metal decking",
  "Light steel framing",
  "Structural timber",
  "Light timber framing",
  "CLT / engineered timber",
  "Masonry structure",
  "Loadbearing blockwork",
  "Secondary steel / lintels / angles",
  "Structural fire protection",
  "Seismic restraint / bracing",
  "Access platforms / catwalks",
  "External waterproofing / tanking",
  "Roofing metal",
  "Roofing membrane",
  "Roofing tiles / slate / shingles",
  "Roof insulation",
  "Roof safety systems",
  "Roof drainage",
  "External wall framing support",
  "External cladding metal",
  "External cladding fibre cement",
  "External cladding masonry veneer",
  "Curtain wall / façade systems",
  "External glazing",
  "Windows",
  "External doors",
  "Roller / sectional / overhead doors",
  "Louvres / screens / shading",
  "Thermal insulation",
  "Acoustic insulation",
  "Air / vapour / weather barriers",
  "Sealants / movement joints",
  "Wall linings",
  "Ceiling linings",
  "Framed partitions",
  "Glazed partitions",
  "Block / masonry partitions",
  "Demountable partitions",
  "Suspended ceilings",
  "Acoustic ceilings / baffles",
  "Access floors",
  "Internal doors / frames",
  "Internal door hardware",
  "Joinery",
  "Benchtops",
  "Toilet partitions / cubicles",
  "Fabricated metalwork",
  "Balustrades / handrails",
  "Lockers / shelving / storage",
  "Window coverings",
  "Internal signage",
  "Fire extinguishers / blankets",
  "Rendering / plastering",
  "Cementitious toppings / screeds",
  "Wet area waterproofing",
  "Ceramic tiling",
  "Stone / terrazzo tiling",
  "Applied wall finishes",
  "Wallcoverings",
  "Resilient flooring",
  "Carpet",
  "Timber flooring",
  "Multilayer board flooring",
  "Floor sanding / finishing",
  "Resin seamless flooring",
  "Painting",
  "Special coatings",
  "Powder coating",
  "Boilers / heaters / chillers",
  "Cooling towers",
  "Pumps / heat exchangers / tanks",
  "Packaged AC",
  "Split systems / room AC",
  "AHUs / FCUs",
  "Ventilation systems",
  "Fans",
  "Ductwork",
  "Duct insulation",
  "Acoustic treatment / attenuators",
  "Grilles / diffusers / VAVs",
  "Mechanical piping",
  "Piping insulation",
  "BMS / controls",
  "Medical gas",
  "Refrigeration / cool rooms",
  "Sanitary fixtures",
  "Tapware",
  "Water heaters",
  "Pumps",
  "Tanks",
  "Above-ground drainage",
  "Below-ground drainage",
  "Stormwater building",
  "Wastewater",
  "Cold water",
  "Hot / heated water",
  "Tempered water systems",
  "Fuel gas",
  "Rainwater harvesting",
  "Greywater systems",
  "Backflow prevention",
  "Hydraulic electrical interfaces",
  "Cable trays / supports / conduits / pits",
  "Main switchboards",
  "Distribution boards",
  "LV power reticulation",
  "General power",
  "Dedicated equipment power",
  "Lighting",
  "Lighting controls",
  "Emergency / exit lighting",
  "PV / solar",
  "Backup generation",
  "UPS",
  "EV charging",
  "Earthing / lightning protection",
  "ICT / data / comms",
  "AV / sound systems",
  "MATV / TV systems",
  "Security / access control / CCTV",
  "Intercom / duress / alarms",
  "Fire pumps",
  "Fire tanks",
  "Fire pipework",
  "Hydrants",
  "Hose reels",
  "Sprinklers",
  "Gaseous suppression",
  "Kitchen / chemical suppression",
  "Fire detection / alarm",
  "EWIS",
  "Fire electrical interfaces",
  "Passive fire stopping",
  "Fire-rated doors / shutters",
  "Lifts",
  "Escalators / travelators",
  "Dumbwaiters / goods lifts",
  "Lift lobbies / interfaces",
  "Lift electrical / controls",
  "BMU / façade access systems",
  "Loading dock equipment",
  "Operable walls",
  "Commercial kitchens",
  "Laboratory fitout systems",
  "Healthcare specialist systems",
  "Clean rooms",
  "Cool rooms / freezer rooms",
  "Warehouse racking / storage systems",
  "Pools / spa / water features",
  "Renewable / energy storage specialty systems",
  "Installation of client-supplied items",
] as const;

const MAT_WORK_TYPES = [
  "Furniture loose",
  "Appliances",
  "Whiteware",
  "Specialist equipment",
  "Client-supplied items",
  "Prime cost sums",
] as const;

const SUB_WORK_TYPES = [
  "Hazardous materials / asbestos",
  "Incoming power",
  "Transformer / kiosk / utility interface",
  "Incoming water",
  "Sewer connection",
  "Stormwater connection",
  "Gas connection",
  "Telecom / fibre connection",
  "External fire ring main",
  "Utility diversions",
] as const;

const DES_WORK_TYPES = [
  "Tendering / procurement setup",
  "Program / planning / reporting",
  "As-built documentation / O&M manuals",
  "Design / shop drawings / coordination",
  "Design / coordination / shop drawings",
  "Authority / consent allowances",
] as const;

const CMS_WORK_TYPES = [
  "Testing / balancing / commissioning",
  "Testing / commissioning",
  "Testing / commissioning / certification",
  "Commissioning / certification",
] as const;

const WST_WORK_TYPES = [
  "Disposal / cartage / tipping",
  "Disposal",
] as const;

const REVIEW_MAT_WORK_TYPES = [
  "Project establishment",
  "Contract preliminaries",
  "Site establishment",
  "Temporary works",
  "Temporary services",
  "Hoardings / fencing / access control",
  "QA / commissioning planning",
  "Health & safety / compliance",
  "Environmental management",
  "Traffic management",
  "Insurances / bonds / permits",
  "Mechanical systems general",
  "Hydraulic systems general",
  "Electrical systems general",
  "Fire services general",
  "Metering / authority fees",
  "Approved variations",
  "Pending variations",
  "Provisional sums",
  "Contingencies",
  "Escalation allowances",
  "Design development allowances",
  "Delay costs",
  "Extension of time costs",
  "Latent conditions",
  "Escalation / price rise adjustments",
  "Risk allowances drawdown",
] as const;

export const WORK_TYPE_DEFAULT_COST_TYPES: Record<string, WorkTypeDefaultCostType> = {
  ...buildCostTypeMap(LAB_WORK_TYPES, "LAB"),
  ...buildCostTypeMap(MAT_WORK_TYPES, "MAT"),
  ...buildCostTypeMap(SUB_WORK_TYPES, "SUB"),
  ...buildCostTypeMap(DES_WORK_TYPES, "DES"),
  ...buildCostTypeMap(CMS_WORK_TYPES, "CMS"),
  ...buildCostTypeMap(WST_WORK_TYPES, "WST"),
  ...buildCostTypeMap(REVIEW_MAT_WORK_TYPES, "MAT", true),
};

export function getWorkTypeDefaultCostType(workType: string | null | undefined): WorkTypeDefaultCostType | null {
  if (!workType) {
    return null;
  }

  return WORK_TYPE_DEFAULT_COST_TYPES[workType] ?? null;
}
