export const COMMERCIAL_LINE_COLUMN_WIDTHS = {
  description: "minmax(240px, 1fr)",
  source: "140px",
  item: "120px",
  quantity: "72px",
  unit: "64px",
  price: "144px",
  amount: "168px",
  action: "44px",
} as const;

export const COMMERCIAL_LINE_GRID_WITH_SOURCE = [
  COMMERCIAL_LINE_COLUMN_WIDTHS.description,
  COMMERCIAL_LINE_COLUMN_WIDTHS.source,
  COMMERCIAL_LINE_COLUMN_WIDTHS.item,
  COMMERCIAL_LINE_COLUMN_WIDTHS.quantity,
  COMMERCIAL_LINE_COLUMN_WIDTHS.unit,
  COMMERCIAL_LINE_COLUMN_WIDTHS.price,
  COMMERCIAL_LINE_COLUMN_WIDTHS.amount,
  COMMERCIAL_LINE_COLUMN_WIDTHS.action,
].join(" ");

export const COMMERCIAL_LINE_GRID_WITHOUT_SOURCE = [
  COMMERCIAL_LINE_COLUMN_WIDTHS.description,
  COMMERCIAL_LINE_COLUMN_WIDTHS.item,
  COMMERCIAL_LINE_COLUMN_WIDTHS.quantity,
  COMMERCIAL_LINE_COLUMN_WIDTHS.unit,
  COMMERCIAL_LINE_COLUMN_WIDTHS.price,
  COMMERCIAL_LINE_COLUMN_WIDTHS.amount,
  COMMERCIAL_LINE_COLUMN_WIDTHS.action,
].join(" ");

export const COMMERCIAL_LINE_TABLE_MIN_WIDTH_WITH_SOURCE = "min-w-[1004px]";
export const COMMERCIAL_LINE_TABLE_MIN_WIDTH_WITHOUT_SOURCE = "min-w-[860px]";
