import {
  type UniversalLearningContainerDefinition,
  type UniversalLearningContainerType,
  UNIVERSAL_LEARNING_CONTAINER_TYPES,
} from "@/lib/universal-learning/types";
import { SUPPLIER_BILL_UCL_SOURCE_TABLES } from "@/lib/universal-learning/supplier-bill-dependencies";

const CATALOG: Record<UniversalLearningContainerType, UniversalLearningContainerDefinition> = {
  pricing_workbook_sheet: {
    containerType: "pricing_workbook_sheet",
    displayName: "Pricing Workbook Sheet",
    primaryReasoningDomain: "commercial_estimating",
    sourceTables: ["opportunity_pricing_workbook_sheets", "opportunity_pricing_worksheets"],
    monthlyCadence: "monthly",
    secondaryTriggers: ["project_won", "exceptional_volume_threshold"],
    strongEvidenceStatuses: ["saved", "updated"],
    workflow: "monthly_pricing_review",
    module: "pricing_worksheets",
  },
  takeoff_measurement: {
    containerType: "takeoff_measurement",
    displayName: "Takeoff Measurement",
    primaryReasoningDomain: "measurement_intelligence",
    sourceTables: ["takeoff_measurements", "takeoff_measurement_points", "takeoff_measurement_events"],
    monthlyCadence: "monthly",
    secondaryTriggers: ["project_won", "exceptional_volume_threshold"],
    strongEvidenceStatuses: ["active", "archived"],
    workflow: "monthly_takeoff_review",
    module: "takeoff",
  },
  project_quote: {
    containerType: "project_quote",
    displayName: "Project Quote",
    primaryReasoningDomain: "commercial_estimating",
    sourceTables: ["opportunity_quotes", "opportunity_quote_line_items", "project_quotes", "project_quote_line_items"],
    monthlyCadence: "monthly",
    secondaryTriggers: ["project_won"],
    strongEvidenceStatuses: ["Accepted", "Sent"],
    workflow: "monthly_project_quote_review",
    module: "project_quotes",
  },
  project_variation: {
    containerType: "project_variation",
    displayName: "Project Variation",
    primaryReasoningDomain: "commercial_recovery",
    sourceTables: [
      "project_variations",
      "project_variation_line_items",
      "project_variation_status_events",
      "project_variation_attachments",
      "project_variation_invoice_items",
    ],
    monthlyCadence: "monthly",
    secondaryTriggers: ["major_claim_cycle_complete"],
    strongEvidenceStatuses: ["Approved", "Invoiced"],
    workflow: "monthly_variation_review",
    module: "variations",
  },
  project_purchase_order: {
    containerType: "project_purchase_order",
    displayName: "Project Purchase Order",
    primaryReasoningDomain: "procurement_commitment",
    sourceTables: ["project_purchase_orders", "project_purchase_order_line_items"],
    monthlyCadence: "monthly",
    secondaryTriggers: ["procurement_package_complete", "exceptional_volume_threshold"],
    strongEvidenceStatuses: ["Approved", "Invoiced"],
    workflow: "monthly_purchase_order_review",
    module: "purchase_orders",
  },
  supplier_invoice: {
    containerType: "supplier_invoice",
    displayName: "Supplier Bill",
    primaryReasoningDomain: "procurement_commitment",
    sourceTables: [...SUPPLIER_BILL_UCL_SOURCE_TABLES],
    monthlyCadence: "monthly",
    secondaryTriggers: ["exceptional_volume_threshold"],
    strongEvidenceStatuses: ["Approved", "Needs Review"],
    workflow: "monthly_supplier_invoice_review",
    module: "supplier_invoices",
  },
  supplier_invoice_allocation: {
    containerType: "supplier_invoice_allocation",
    displayName: "Supplier Invoice Allocation",
    primaryReasoningDomain: "cost_attribution",
    sourceTables: [
      "supplier_invoice_line_allocations",
      "supplier_invoices",
      "supplier_invoice_lines",
      "supplier_invoice_documents",
      "supplier_invoice_purchase_order_matches",
      "project_purchase_orders",
      "project_purchase_order_line_items",
      "project_actual_cost_events",
      "organization_projects",
      "organization_clients",
      "organization_suppliers",
    ],
    monthlyCadence: "monthly",
    secondaryTriggers: ["procurement_package_complete", "exceptional_volume_threshold"],
    strongEvidenceStatuses: ["approved", "resolved", "auto_approved"],
    workflow: "monthly_supplier_invoice_allocation_review",
    module: "supplier_invoices",
  },
  project_actual_cost_event: {
    containerType: "project_actual_cost_event",
    displayName: "Project Actual Cost Event",
    primaryReasoningDomain: "cost_attribution",
    sourceTables: ["project_actual_cost_events"],
    monthlyCadence: "monthly",
    secondaryTriggers: ["major_claim_cycle_complete", "exceptional_volume_threshold"],
    strongEvidenceStatuses: ["posted", "reversed"],
    workflow: "monthly_actual_cost_review",
    module: "actual_costs",
  },
  organization_material: {
    containerType: "organization_material",
    displayName: "Organization Material",
    primaryReasoningDomain: "catalogue_intelligence",
    sourceTables: ["organization_materials", "organization_material_supplier_prices"],
    monthlyCadence: "monthly",
    secondaryTriggers: ["procurement_package_complete"],
    strongEvidenceStatuses: ["user_confirmed", "active"],
    workflow: "monthly_material_review",
    module: "materials",
  },
  material_import_batch: {
    containerType: "material_import_batch",
    displayName: "Organization Material Import Batch",
    primaryReasoningDomain: "catalogue_intelligence",
    sourceTables: ["organization_material_import_batches", "organization_material_import_rows"],
    monthlyCadence: "monthly",
    secondaryTriggers: ["procurement_package_complete", "exceptional_volume_threshold"],
    strongEvidenceStatuses: ["approved", "partially_approved"],
    workflow: "monthly_material_import_review",
    module: "materials",
  },
  project_claim: {
    containerType: "project_claim",
    displayName: "Payment Claim",
    primaryReasoningDomain: "commercial_recovery",
    sourceTables: [
      "project_claims",
      "project_claim_line_items",
      "organization_projects",
      "organization_clients",
      "project_quotes",
      "project_variations",
      "retention_claim_allocations",
      "organization_accounting_documents",
    ],
    monthlyCadence: "monthly",
    secondaryTriggers: ["major_claim_cycle_complete"],
    strongEvidenceStatuses: ["Submitted", "Paid"],
    workflow: "monthly_claim_review",
    module: "claims",
  },
  project_time_sheet_entry: {
    containerType: "project_time_sheet_entry",
    displayName: "Project Time Sheet Entry",
    primaryReasoningDomain: "project_delivery",
    sourceTables: ["project_time_sheet_entries", "project_time_sheet_events"],
    monthlyCadence: "monthly",
    secondaryTriggers: ["project_complete"],
    strongEvidenceStatuses: ["closed", "clocked_out"],
    workflow: "monthly_timesheet_review",
    module: "timesheets",
  },
  project_quality_issue: {
    containerType: "project_quality_issue",
    displayName: "Project Quality Issue",
    primaryReasoningDomain: "quality_assurance",
    sourceTables: ["project_quality_issues"],
    monthlyCadence: "monthly",
    secondaryTriggers: ["project_complete"],
    strongEvidenceStatuses: ["Complete", "In Progress"],
    workflow: "monthly_quality_issue_review",
    module: "quality_assurance",
  },
  project_quality_inspection: {
    containerType: "project_quality_inspection",
    displayName: "Project Quality Inspection",
    primaryReasoningDomain: "quality_assurance",
    sourceTables: ["project_quality_inspections", "project_quality_inspection_items"],
    monthlyCadence: "monthly",
    secondaryTriggers: ["project_complete"],
    strongEvidenceStatuses: ["completed", "scheduled"],
    workflow: "monthly_quality_inspection_review",
    module: "quality_assurance",
  },
  project_quality_sign_off: {
    containerType: "project_quality_sign_off",
    displayName: "Project Quality Sign Off",
    primaryReasoningDomain: "quality_assurance",
    sourceTables: ["project_quality_sign_offs"],
    monthlyCadence: "monthly",
    secondaryTriggers: ["project_complete"],
    strongEvidenceStatuses: ["Signed", "Requested"],
    workflow: "monthly_quality_signoff_review",
    module: "quality_assurance",
  },
  task: {
    containerType: "task",
    displayName: "Task",
    primaryReasoningDomain: "project_delivery",
    sourceTables: ["project_job_todos", "task_activity_log", "task_comments", "task_attachments"],
    monthlyCadence: "monthly",
    secondaryTriggers: ["project_complete"],
    strongEvidenceStatuses: ["completed", "archived"],
    workflow: "monthly_task_review",
    module: "tasks",
  },
};

export const UNIVERSAL_LEARNING_CONTAINER_CATALOG = CATALOG;

export function getUniversalLearningContainerDefinition(
  containerType: UniversalLearningContainerType,
): UniversalLearningContainerDefinition {
  return CATALOG[containerType];
}

export function listUniversalLearningContainerDefinitions() {
  return UNIVERSAL_LEARNING_CONTAINER_TYPES.map((containerType) => CATALOG[containerType]);
}
