import { describe, expect, it, vi } from "vitest";
vi.mock("server-only", () => ({}));
import {
  assessCostConstructionIntelligenceQuality,
  buildCostConstructionNormalization,
  buildCostConstructionIntelligenceIdempotencyKey,
  buildCostConstructionIntelligenceSchema,
  buildCostConstructionIntelligenceSnapshot,
  EMPTY_COST_CONSTRUCTION_INTELLIGENCE,
  normalizeCostConstructionIntelligenceResult,
} from "@/lib/cost-construction-intelligence";

describe("cost construction intelligence helpers", () => {
  it("builds deterministic idempotency keys per source revision", () => {
    expect(
      buildCostConstructionIntelligenceIdempotencyKey({
        sourceType: "organization_material",
        sourceId: "material-1",
        revisionToken: "2026-06-21T00:00:00.000Z",
      }),
    ).toBe(
      "cost-construction-intelligence:organization_material:material-1:root:2026-06-21T00:00:00.000Z",
    );
  });

  it("normalizes structured AI output into safe nullable metadata", () => {
    expect(
      normalizeCostConstructionIntelligenceResult({
        trade: "Wall Linings",
        subtrade: "Plasterboard",
        work_package: "Internal Wall Linings",
        system: "Plasterboard Walls",
        assembly: "Steel Stud Wall",
        component: "Wall Lining Board",
        product_family: "Standard Plasterboard",
        product: "13mm GIB Standard",
        manufacturer: null,
        brand: "GIB",
        supplier: "Placemakers",
        activity: "Supply",
        install_method: "",
        application_area: "Internal partition walls",
        location_context: "",
        project_context: "Apartment fitout",
        likely_use: "Internal partition walls",
        related_components: ["Rondo 64mm Stud", 4, ""],
        exclusions_or_risks: ["lead_time", 4, ""],
        normalization_tokens: ["13mm GIB Board", "Wall Linings", ""],
        confidence: 1.4,
        reasoning: "Description references GIB standard sheets.",
        evidence: ["13mm GIB Standard", null],
      }),
    ).toEqual({
      trade: "Wall Linings",
      subtrade: "Plasterboard",
      work_package: "Internal Wall Linings",
      system: "Plasterboard Walls",
      assembly: "Steel Stud Wall",
      component: "Wall Lining Board",
      product_family: "Standard Plasterboard",
      product: "13mm GIB Standard",
      manufacturer: null,
      brand: "GIB",
      supplier: "Placemakers",
      activity: "Supply",
      install_method: null,
      application_area: "Internal partition walls",
      location_context: null,
      project_context: "Apartment fitout",
      likely_use: "Internal partition walls",
      related_components: ["Rondo 64mm Stud"],
      exclusions_or_risks: ["lead_time"],
      normalization_tokens: ["13mm_gib_board", "wall_linings"],
      confidence: 1,
      reasoning: "Description references GIB standard sheets.",
      evidence: ["13mm GIB Standard"],
    });
  });

  it("normalizes weird null-like provider strings to null across nullable fields", () => {
    expect(
      normalizeCostConstructionIntelligenceResult({
        trade: "Suspended Ceilings",
        subtrade: "Grid Ceiling Systems",
        work_package: "Ceiling Package",
        system: "Suspended Ceiling Grid System",
        assembly: "Keylock Grid Assembly",
        component: "Ceiling Grid",
        product_family: "Keylock Grid",
        product: "Rondo Keylock Grid",
        manufacturer: "Rondo Building Services",
        brand: "Rondo",
        supplier: "\nnull",
        activity: "Install",
        install_method: "},{",
        application_area: "Interior ceiling plane",
        location_context: "\bnull",
        project_context: "N/A",
        likely_use: "Commercial suspended ceiling grid",
        related_components: ["Perimeter trim", "},{"],
        exclusions_or_risks: ["Unknown", "Service penetrations"],
        normalization_tokens: ["Rondo Keylock", "null", "},{"],
        confidence: 0.91,
        reasoning: "Unknown",
        evidence: ["Keylock", "\nnull", "100 m2"],
      }),
    ).toEqual({
      trade: "Suspended Ceilings",
      subtrade: "Grid Ceiling Systems",
      work_package: "Ceiling Package",
      system: "Suspended Ceiling Grid System",
      assembly: "Keylock Grid Assembly",
      component: "Ceiling Grid",
      product_family: "Keylock Grid",
      product: "Rondo Keylock Grid",
      manufacturer: "Rondo Building Services",
      brand: "Rondo",
      supplier: null,
      activity: "Install",
      install_method: null,
      application_area: "Interior ceiling plane",
      location_context: null,
      project_context: null,
      likely_use: "Commercial suspended ceiling grid",
      related_components: ["Perimeter trim"],
      exclusions_or_risks: ["Service penetrations"],
      normalization_tokens: ["rondo_keylock"],
      confidence: 0.91,
      reasoning: null,
      evidence: ["Keylock", "100 m2"],
    });
  });

  it("preserves valid nullable string values while nulling punctuation-only garbage", () => {
    const result = normalizeCostConstructionIntelligenceResult({
      trade: "Wall Linings",
      subtrade: "Partitions",
      work_package: "Office Fitout Partitions",
      system: "GIB and Rondo partition system",
      assembly: "Steel stud partition wall",
      component: "Head track / deflection head",
      product_family: "13mm GIB Standard",
      product: "13mm GIB Standard plasterboard",
      manufacturer: "Winstone Wallboards",
      brand: "GIB",
      supplier: "PlaceMakers",
      activity: "Supply and install",
      install_method: "Screw-fixed to Rondo studs / tracks",
      application_area: "Internal partitions",
      location_context: "Level 2 office fitout",
      project_context: "Auckland commercial interiors",
      likely_use: "Office fitout partition lining",
      related_components: ["Rondo 64mm studs", "..."],
      exclusions_or_risks: ["Acoustic rating not specified", "---"],
      normalization_tokens: ["GIB Standard", "Rondo studs", "///"],
      confidence: 0.87,
      reasoning: "Uses NZ partition terminology and valid supplier/manufacturer references.",
      evidence: ["13mm GIB Standard", "Rondo studs", "___"],
    });

    expect(result).toMatchObject({
      supplier: "PlaceMakers",
      install_method: "Screw-fixed to Rondo studs / tracks",
      project_context: "Auckland commercial interiors",
      location_context: "Level 2 office fitout",
      reasoning: "Uses NZ partition terminology and valid supplier/manufacturer references.",
      related_components: ["Rondo 64mm studs"],
      exclusions_or_risks: ["Acoustic rating not specified"],
      normalization_tokens: ["gib_standard", "rondo_studs"],
      evidence: ["13mm GIB Standard", "Rondo studs"],
    });
  });

  it("defines the full structured construction intelligence schema", () => {
    const schema = buildCostConstructionIntelligenceSchema();

    expect(schema.required).toEqual([
      "trade",
      "subtrade",
      "work_package",
      "system",
      "assembly",
      "component",
      "product_family",
      "product",
      "manufacturer",
      "brand",
      "supplier",
      "activity",
      "install_method",
      "application_area",
      "location_context",
      "project_context",
      "likely_use",
      "related_components",
      "exclusions_or_risks",
      "normalization_tokens",
      "confidence",
      "reasoning",
      "evidence",
    ]);
  });

  it("prepares a source-row snapshot without changing financial routing data", () => {
    const snapshot = buildCostConstructionIntelligenceSnapshot({
      classification: {
        trade: "Cladding",
        subtrade: "Metal Cladding",
        work_package: "External Cladding",
        system: "Metal Cladding",
        assembly: "Facade Cladding Build-Up",
        component: "Cladding Sheet",
        product_family: "Profiled Steel Cladding",
        product: "Coloursteel",
        manufacturer: null,
        brand: "Coloursteel",
        supplier: null,
        activity: "Supply",
        install_method: null,
        application_area: "External walls",
        location_context: null,
        project_context: null,
        likely_use: "Facade cladding",
        related_components: [],
        exclusions_or_risks: [],
        normalization_tokens: ["Coloursteel Cladding", "External Cladding"],
        confidence: 0.81,
        reasoning: "Matched from product wording.",
        evidence: ["coloursteel"],
      },
      event: {
        id: "event-1",
        sourceType: "cost_item",
        documentContext: {
          module: "cost_items",
        },
        classificationVersion: 1,
      },
      provider: "openai",
      model: "gpt-5.5",
      classifiedAt: "2026-06-21T12:00:00.000Z",
    });

    expect(snapshot).toMatchObject({
      sourceType: "cost_item",
      sourceEventId: "event-1",
      provider: "openai",
      model: "gpt-5.5",
      trade: "Cladding",
      product: "Coloursteel",
      normalization: expect.objectContaining({
        productSignature: "coloursteel",
      }),
    });
    expect("tradesstackCostCode" in snapshot).toBe(false);
  });

  it("builds deterministic normalization signatures for future memory grouping", () => {
    const normalization = buildCostConstructionNormalization({
      trade: "Wall Linings",
      subtrade: "Plasterboard",
      work_package: "Internal Wall Linings",
      system: "Plasterboard Walls",
      assembly: "Steel Stud Wall",
      component: "Wall Lining Board",
      product_family: "Standard Plasterboard",
      product: "13mm GIB Standard",
      manufacturer: null,
      brand: "GIB",
      supplier: "PlaceMakers",
      activity: "Supply",
      install_method: "Screw-fixed",
      application_area: "Internal partition walls",
      location_context: "Level 2 apartments",
      project_context: "Apartment fitout",
      likely_use: "Internal partition walls",
      related_components: ["Rondo 64mm Stud", "Track", "Screws"],
      exclusions_or_risks: ["Lead time"],
      normalization_tokens: ["13mm GIB Board", "Wall Linings"],
      confidence: 0.94,
      reasoning: "Explicit board wording.",
      evidence: ["13mm", "GIB"],
    });

    expect(normalization).toEqual({
      tokens: expect.arrayContaining([
        "13mm_gib_board",
        "wall_linings",
        "plasterboard_walls",
        "rondo_64mm_stud",
      ]),
      productSignature: "13mm_gib_standard",
      constructionSignature:
        "wall_linings__plasterboard__plasterboard_walls__steel_stud_wall__wall_lining_board__13mm_gib_standard__supply__internal_partition_walls",
      groupingKeys: expect.arrayContaining([
        "wall_linings_plasterboard_walls",
        "placemakers_13mm_gib_standard",
      ]),
    });
  });

  it("exports a stable empty metadata object for non-null source row defaults", () => {
    expect(EMPTY_COST_CONSTRUCTION_INTELLIGENCE).toEqual({});
  });

  it("rejects all-null construction output for substantive records", () => {
    const classification = normalizeCostConstructionIntelligenceResult({
      trade: null,
      subtrade: null,
      work_package: null,
      system: null,
      assembly: null,
      component: null,
      product_family: null,
      product: null,
      manufacturer: null,
      brand: null,
      supplier: null,
      activity: null,
      install_method: null,
      application_area: null,
      location_context: null,
      project_context: null,
      likely_use: null,
      related_components: [],
      exclusions_or_risks: [],
      normalization_tokens: [],
      confidence: null,
      reasoning: null,
      evidence: [],
    });

    expect(classification).not.toBeNull();
    expect(
      assessCostConstructionIntelligenceQuality({
        classification: classification!,
        description: "13mm GIB Standard plasterboard sheets for internal partitions",
        sourceType: "organization_material",
        tradesstackCostCode: "100",
      }),
    ).toEqual({
      isAcceptable: false,
      coreFieldCount: 0,
      reason: "quality_failed_all_core_fields_null",
    });
  });

  it("allows sparse claim or retention intelligence when activity/context is present", () => {
    const classification = normalizeCostConstructionIntelligenceResult({
      trade: null,
      subtrade: null,
      work_package: null,
      system: null,
      assembly: null,
      component: null,
      product_family: null,
      product: null,
      manufacturer: null,
      brand: null,
      supplier: null,
      activity: "Claim",
      install_method: null,
      application_area: null,
      location_context: null,
      project_context: null,
      likely_use: null,
      related_components: [],
      exclusions_or_risks: [],
      normalization_tokens: ["payment claim"],
      confidence: 0.72,
      reasoning: "Payment claim wording is explicit.",
      evidence: ["payment claim"],
    });

    expect(
      assessCostConstructionIntelligenceQuality({
        classification: classification!,
        description: "Payment claim no. 4",
        sourceType: "cost_item",
        tradesstackCostCode: "600",
      }).isAcceptable,
    ).toBe(true);
  });

  it("normalizes Unknown, N/A, and slash placeholders to null", () => {
    expect(
      normalizeCostConstructionIntelligenceResult({
        trade: "Unknown",
        subtrade: "N/A",
        work_package: "Unclear",
        system: "/",
        assembly: "-",
        component: "none",
        product_family: "Not specified",
        product: "13mm GIB Standard",
        manufacturer: "Unknown",
        brand: "GIB",
        supplier: "N/A",
        activity: "Supply",
        install_method: "Unknown",
        application_area: "unspecified",
        location_context: "Unknown",
        project_context: "NA",
        likely_use: "Internal partition walls",
        related_components: ["Unknown", "Track"],
        exclusions_or_risks: ["N/A", "Lead time"],
        normalization_tokens: ["Unknown", "13mm GIB Board"],
        confidence: 0.8,
        reasoning: "Unknown",
        evidence: ["N/A", "13mm"],
      }),
    ).toEqual({
      trade: null,
      subtrade: null,
      work_package: null,
      system: null,
      assembly: null,
      component: null,
      product_family: null,
      product: "13mm GIB Standard",
      manufacturer: null,
      brand: "GIB",
      supplier: null,
      activity: "Supply",
      install_method: null,
      application_area: null,
      location_context: null,
      project_context: null,
      likely_use: "Internal partition walls",
      related_components: ["Track"],
      exclusions_or_risks: ["Lead time"],
      normalization_tokens: ["13mm_gib_board"],
      confidence: 0.8,
      reasoning: null,
      evidence: ["13mm"],
    });
  });

  it("keeps sparse payment-claim outputs useful after unknown placeholders are nulled", () => {
    const classification = normalizeCostConstructionIntelligenceResult({
      trade: "Unknown",
      subtrade: "Unknown",
      work_package: "Unknown",
      system: "Unknown",
      assembly: "Unknown",
      component: "Unknown",
      product_family: "Unknown",
      product: "Unknown",
      manufacturer: "Unknown",
      brand: "Unknown",
      supplier: "Unknown",
      activity: "Payment Claim",
      install_method: "Unknown",
      application_area: "Unknown",
      location_context: "Unknown",
      project_context: "Unknown",
      likely_use: "Unknown",
      related_components: [],
      exclusions_or_risks: [],
      normalization_tokens: ["payment claim"],
      confidence: 0.05,
      reasoning: "Placeholder payment-claim row.",
      evidence: ["TEST 123"],
    });

    expect(classification).toMatchObject({
      trade: null,
      system: null,
      product: null,
      activity: "Payment Claim",
      likely_use: null,
    });
    expect(
      assessCostConstructionIntelligenceQuality({
        classification: classification!,
        description: "TEST 123",
        sourceType: "cost_item",
        tradesstackCostCode: "600",
      }).isAcceptable,
    ).toBe(true);
  });

  it.each([
    {
      label: "13mm GIB plasterboard sheets",
      input: {
        trade: "Wall Linings",
        subtrade: "Plasterboard",
        work_package: "Internal Wall Linings",
        system: "Plasterboard Walls",
        assembly: "Steel Stud Wall",
        component: "Wall Lining Board",
        product_family: "Standard Plasterboard",
        product: "13mm GIB Standard",
        manufacturer: null,
        brand: "GIB",
        supplier: "Placemakers",
        activity: "Supply",
        install_method: null,
        application_area: "Internal partition walls",
        location_context: null,
        project_context: null,
        likely_use: "Internal partition walls",
        related_components: ["Rondo 64mm Stud"],
        exclusions_or_risks: ["lead_time"],
        normalization_tokens: ["13mm GIB Board"],
        confidence: 0.91,
        reasoning: "Explicit board product wording.",
        evidence: ["13mm", "GIB", "plasterboard"],
      },
      expected: {
        trade: "Wall Linings",
        system: "Plasterboard Walls",
        brand: "GIB",
        activity: "Supply",
      },
    },
    {
      label: "Coloursteel cladding",
      input: {
        trade: "Cladding",
        subtrade: "Metal Cladding",
        work_package: "External Cladding",
        system: "Metal Cladding",
        assembly: "Facade Cladding Build-Up",
        component: "Cladding Sheet",
        product_family: "Profiled Steel Cladding",
        product: "Coloursteel wall cladding",
        manufacturer: "New Zealand Steel",
        brand: "Coloursteel",
        supplier: null,
        activity: "Supply",
        install_method: "screw-fixed",
        application_area: "External walls",
        location_context: null,
        project_context: null,
        likely_use: "Facade cladding",
        related_components: [],
        exclusions_or_risks: ["lead_time"],
        normalization_tokens: ["Coloursteel Cladding"],
        confidence: 0.86,
        reasoning: "Brand and system are explicit.",
        evidence: ["Coloursteel", "cladding"],
      },
      expected: {
        trade: "Cladding",
        system: "Metal Cladding",
        brand: "Coloursteel",
      },
    },
    {
      label: "Rondo steel studs",
      input: {
        trade: "Wall Linings",
        subtrade: "Steel Stud Framing",
        work_package: "Internal Wall Framing",
        system: "Steel Stud Framing",
        assembly: "Steel Stud Wall",
        component: "Stud",
        product_family: "Light Gauge Stud",
        product: "Rondo steel studs",
        manufacturer: null,
        brand: "Rondo",
        supplier: null,
        activity: "Supply",
        install_method: null,
        application_area: "Internal walls",
        location_context: null,
        project_context: null,
        likely_use: "Wall framing",
        related_components: ["Track"],
        exclusions_or_risks: [],
        normalization_tokens: ["Rondo Stud"],
        confidence: 0.84,
        reasoning: "Brand and framing component are explicit.",
        evidence: ["Rondo", "studs"],
      },
      expected: {
        system: "Steel Stud Framing",
        brand: "Rondo",
      },
    },
    {
      label: "scaffold hire",
      input: {
        trade: "Access Systems",
        subtrade: "Scaffolding",
        work_package: "Temporary Access",
        system: "Scaffolding Access",
        assembly: "Perimeter Scaffold",
        component: "Scaffold Hire",
        product_family: "Temporary Access Equipment",
        product: "Scaffold hire",
        manufacturer: null,
        brand: null,
        supplier: "Safe Access Ltd",
        activity: "Hire",
        install_method: null,
        application_area: "Site perimeter",
        location_context: null,
        project_context: null,
        likely_use: "Temporary access",
        related_components: [],
        exclusions_or_risks: ["access_dependency"],
        normalization_tokens: ["Scaffold Hire"],
        confidence: 0.79,
        reasoning: "Hire framing is explicit.",
        evidence: ["scaffold", "hire"],
      },
      expected: {
        system: "Scaffolding Access",
        activity: "Hire",
        component: "Scaffold Hire",
      },
    },
    {
      label: "subcontractor supply and install package",
      input: {
        trade: "Partitions",
        subtrade: "Wall Framing",
        work_package: "Partition Package",
        system: "Wall Framing",
        assembly: "Internal Partition Build-Up",
        component: "Partition Package",
        product_family: "Framing Package",
        product: "Subcontractor supply and install package",
        manufacturer: null,
        brand: null,
        supplier: "ABC Interiors",
        activity: "Supply and Install",
        install_method: "subcontract_install",
        application_area: "Internal partitions",
        location_context: null,
        project_context: null,
        likely_use: "Partition package delivery",
        related_components: ["Stud", "Track", "Board"],
        exclusions_or_risks: ["interface_risk"],
        normalization_tokens: ["Supply Install Package"],
        confidence: 0.82,
        reasoning: "Package wording is explicit.",
        evidence: ["subcontractor", "supply and install"],
      },
      expected: {
        trade: "Partitions",
        activity: "Supply and Install",
        work_package: "Partition Package",
      },
    },
    {
      label: "payment claim",
      input: {
        trade: null,
        subtrade: null,
        work_package: null,
        system: null,
        assembly: null,
        component: "Claim",
        product_family: null,
        product: "Progress payment claim",
        manufacturer: null,
        brand: null,
        supplier: null,
        activity: "Claim",
        install_method: null,
        application_area: null,
        location_context: null,
        project_context: null,
        likely_use: null,
        related_components: [],
        exclusions_or_risks: ["cash_flow"],
        normalization_tokens: ["Payment Claim"],
        confidence: 0.76,
        reasoning: "Document context indicates claim workflow.",
        evidence: ["payment claim"],
      },
      expected: {
        activity: "Claim",
        component: "Claim",
      },
    },
    {
      label: "retention release",
      input: {
        trade: null,
        subtrade: null,
        work_package: null,
        system: null,
        assembly: null,
        component: "Retention Release",
        product_family: null,
        product: "Retention release",
        manufacturer: null,
        brand: null,
        supplier: null,
        activity: "Release",
        install_method: null,
        application_area: null,
        location_context: null,
        project_context: null,
        likely_use: null,
        related_components: [],
        exclusions_or_risks: ["cash_flow"],
        normalization_tokens: ["Retention Release"],
        confidence: 0.74,
        reasoning: "Retention wording is explicit.",
        evidence: ["retention", "release"],
      },
      expected: {
        activity: "Release",
        component: "Retention Release",
      },
    },
  ])("supports useful structured outputs for $label", ({ input, expected }) => {
    expect(normalizeCostConstructionIntelligenceResult(input)).toMatchObject(expected);
  });
});
