"use client";

import { Footer } from "@/components/marketing/Footer";
import { Navbar } from "@/components/marketing/Navbar";
import { useAuth } from "@/hooks/use-auth";
import { akzidenzBlack, bertholdExtraBoldCondensed } from "@/lib/fonts";

export default function TermsOfServicePage() {
  const { session } = useAuth();

  return (
    <div className="min-h-screen overflow-x-hidden bg-[linear-gradient(180deg,#04234D_0%,#062A5C_100%)] text-white">
      <main>
        <Navbar session={session} loginHref="/login" />

        <section className="px-6 pb-16 pt-28 lg:px-16 lg:pt-32">
          <div className="mx-auto w-full max-w-[1000px]">
            <h1
              className={`${bertholdExtraBoldCondensed.className} text-[44px] font-bold uppercase leading-[0.95] tracking-[-0.02em] text-white sm:text-[58px] lg:text-[72px]`}
            >
              Terms of Service
            </h1>
            <p className={`${akzidenzBlack.className} mt-4 text-base text-white/80`}>Last Updated: March 10, 2026</p>

            <div className="mt-8 rounded-2xl border border-white/10 bg-[rgba(8,34,72,0.82)] p-6 shadow-[0_20px_60px_rgba(0,0,0,0.35)] sm:p-8">
              <div className={`${akzidenzBlack.className} space-y-7 text-[16px] leading-[1.75] text-white/86`}>
                <p>
                  These Terms of Service (&quot;Terms&quot;) govern your access to and use of the TradesStack website, platform, and related
                  services (collectively, the &quot;Service&quot;).
                </p>
                <p>
                  TradesStack provides AI-assisted tools designed to help construction professionals organize, analyze, and review project
                  documentation.
                </p>
                <p>By accessing or using the Service, you agree to these Terms. If you do not agree, you must not use the Service.</p>

                <section>
                  <h2 className="text-[26px] font-semibold uppercase tracking-[0.02em] text-[#F74917]">1. Platform Overview</h2>
                  <p className="mt-3">
                    TradesStack is a cloud-based software platform designed for construction professionals including builders, estimators,
                    quantity surveyors, and project managers.
                  </p>
                  <p className="mt-2">The platform provides tools that assist with:</p>
                  <ul className="mt-2 list-disc space-y-1 pl-6">
                    <li>Construction drawing analysis</li>
                    <li>Trade pack generation</li>
                    <li>Scope generation</li>
                    <li>Drawing change detection</li>
                    <li>AI-assisted construction questions</li>
                  </ul>
                  <p className="mt-2">
                    TradesStack provides software tools only and does not provide professional engineering, architectural, legal, quantity
                    surveying, or construction advice.
                  </p>
                </section>

                <section>
                  <h2 className="text-[26px] font-semibold uppercase tracking-[0.02em] text-[#F74917]">2. No Professional Advice</h2>
                  <p className="mt-3">TradesStack does not provide professional construction advice.</p>
                  <p className="mt-2">All outputs generated by the platform are automated software-generated assistance only.</p>
                  <p className="mt-2">TradesStack does not act as:</p>
                  <ul className="mt-2 list-disc space-y-1 pl-6">
                    <li>a builder</li>
                    <li>a quantity surveyor</li>
                    <li>an engineer</li>
                    <li>an architect</li>
                    <li>a project manager</li>
                    <li>a construction consultant</li>
                  </ul>
                  <p className="mt-2">Users remain solely responsible for all professional decisions made in connection with construction projects.</p>
                </section>

                <section>
                  <h2 className="text-[26px] font-semibold uppercase tracking-[0.02em] text-[#F74917]">3. AI Output Disclaimer</h2>
                  <p className="mt-3">TradesStack uses artificial intelligence and automated systems to analyze documents and generate outputs.</p>
                  <p className="mt-2">AI-generated outputs may include:</p>
                  <ul className="mt-2 list-disc space-y-1 pl-6">
                    <li>scope summaries</li>
                    <li>exclusions</li>
                    <li>coordination risks</li>
                    <li>pricing guidance</li>
                    <li>change detection results</li>
                    <li>responses from the AI assistant</li>
                  </ul>
                  <p className="mt-2">These outputs:</p>
                  <ul className="mt-2 list-disc space-y-1 pl-6">
                    <li>may contain errors</li>
                    <li>may be incomplete</li>
                    <li>may misinterpret drawings or specifications</li>
                    <li>may omit relevant information</li>
                  </ul>
                  <p className="mt-2">AI outputs must always be independently reviewed and verified by qualified professionals.</p>
                  <p className="mt-2">Users must verify all information against:</p>
                  <ul className="mt-2 list-disc space-y-1 pl-6">
                    <li>project drawings</li>
                    <li>specifications</li>
                    <li>contracts</li>
                    <li>building codes</li>
                    <li>applicable standards</li>
                  </ul>
                  <p className="mt-2">TradesStack does not guarantee the accuracy, completeness, or reliability of AI-generated content.</p>
                </section>

                <section>
                  <h2 className="text-[26px] font-semibold uppercase tracking-[0.02em] text-[#F74917]">4. User Responsibility for Construction Decisions</h2>
                  <p className="mt-3">Users are solely responsible for:</p>
                  <ul className="mt-2 list-disc space-y-1 pl-6">
                    <li>project pricing</li>
                    <li>tender submissions</li>
                    <li>construction scope definitions</li>
                    <li>contractual obligations</li>
                    <li>compliance with building codes</li>
                    <li>regulatory requirements</li>
                    <li>construction decisions</li>
                  </ul>
                  <p className="mt-2">TradesStack is a decision-support tool only.</p>
                  <p className="mt-2">
                    All project decisions must be made by qualified professionals based on full project documentation and professional
                    judgment.
                  </p>
                </section>

                <section>
                  <h2 className="text-[26px] font-semibold uppercase tracking-[0.02em] text-[#F74917]">5. Uploaded Project Documents</h2>
                  <p className="mt-3">Users may upload project documentation such as:</p>
                  <ul className="mt-2 list-disc space-y-1 pl-6">
                    <li>construction drawings</li>
                    <li>tender documentation</li>
                    <li>design information</li>
                  </ul>
                  <p className="mt-2">Users confirm that:</p>
                  <ul className="mt-2 list-disc space-y-1 pl-6">
                    <li>they have the legal right to upload the documents</li>
                    <li>documents do not violate confidentiality obligations</li>
                    <li>documents do not infringe third-party rights</li>
                  </ul>
                  <p className="mt-2">Users retain ownership of uploaded documents.</p>
                  <p className="mt-2">
                    By uploading documents, users grant TradesStack permission to process the documents for the purpose of providing the
                    Service.
                  </p>
                  <p className="mt-2">TradesStack does not claim ownership of user content.</p>
                </section>

                <section>
                  <h2 className="text-[26px] font-semibold uppercase tracking-[0.02em] text-[#F74917]">6. Multi-Tenant Platform and Data Access</h2>
                  <p className="mt-3">TradesStack operates as a multi-tenant platform.</p>
                  <p className="mt-2">Users belong to organizations and collaborate within projects.</p>
                  <p className="mt-2">Access to data is controlled through:</p>
                  <ul className="mt-2 list-disc space-y-1 pl-6">
                    <li>authentication</li>
                    <li>organization membership</li>
                    <li>project-level permissions</li>
                    <li>database security policies</li>
                  </ul>
                  <p className="mt-2">Users are responsible for managing access permissions within their organizations.</p>
                </section>

                <section>
                  <h2 className="text-[26px] font-semibold uppercase tracking-[0.02em] text-[#F74917]">7. Acceptable Use</h2>
                  <p className="mt-3">Users must not:</p>
                  <ul className="mt-2 list-disc space-y-1 pl-6">
                    <li>misuse the platform</li>
                    <li>attempt to bypass security protections</li>
                    <li>upload malicious files</li>
                    <li>attempt to access other organizations’ data</li>
                    <li>abuse AI processing limits</li>
                    <li>reverse engineer platform functionality</li>
                  </ul>
                  <p className="mt-2">TradesStack may suspend or terminate accounts that violate these rules.</p>
                </section>

                <section>
                  <h2 className="text-[26px] font-semibold uppercase tracking-[0.02em] text-[#F74917]">8. Service Availability</h2>
                  <p className="mt-3">TradesStack is provided as an online software service.</p>
                  <p className="mt-2">We aim to maintain reliable access but do not guarantee uninterrupted availability.</p>
                  <p className="mt-2">Service interruptions may occur due to:</p>
                  <ul className="mt-2 list-disc space-y-1 pl-6">
                    <li>maintenance</li>
                    <li>infrastructure failures</li>
                    <li>third-party service disruptions</li>
                    <li>system updates</li>
                  </ul>
                  <p className="mt-2">TradesStack is not responsible for losses caused by service downtime.</p>
                </section>

                <section>
                  <h2 className="text-[26px] font-semibold uppercase tracking-[0.02em] text-[#F74917]">9. Limitation of Liability</h2>
                  <p className="mt-3">To the maximum extent permitted by law, TradesStack and its operators will not be liable for any:</p>
                  <ul className="mt-2 list-disc space-y-1 pl-6">
                    <li>construction defects</li>
                    <li>scope omissions</li>
                    <li>pricing errors</li>
                    <li>tender mistakes</li>
                    <li>contract disputes</li>
                    <li>regulatory compliance failures</li>
                    <li>project delays</li>
                    <li>financial losses</li>
                  </ul>
                  <p className="mt-2">resulting from the use of the platform or reliance on its outputs.</p>
                  <p className="mt-2">TradesStack is provided &quot;as is&quot; without warranties of any kind.</p>
                </section>

                <section>
                  <h2 className="text-[26px] font-semibold uppercase tracking-[0.02em] text-[#F74917]">10. Financial Liability Cap</h2>
                  <p className="mt-3">
                    To the maximum extent permitted by law, the total liability of TradesStack for any claims related to the Service will
                    not exceed the amount paid by the user for the Service during the 12 months preceding the claim.
                  </p>
                </section>

                <section>
                  <h2 className="text-[26px] font-semibold uppercase tracking-[0.02em] text-[#F74917]">11. Indemnification</h2>
                  <p className="mt-3">
                    Users agree to indemnify and hold harmless TradesStack and its operators from any claims, damages, or liabilities
                    arising from:
                  </p>
                  <ul className="mt-2 list-disc space-y-1 pl-6">
                    <li>reliance on AI-generated outputs</li>
                    <li>construction decisions based on platform outputs</li>
                    <li>misuse of the platform</li>
                    <li>unauthorized document uploads</li>
                    <li>violations of these Terms</li>
                  </ul>
                </section>

                <section>
                  <h2 className="text-[26px] font-semibold uppercase tracking-[0.02em] text-[#F74917]">12. Fees and Subscriptions</h2>
                  <p className="mt-3">Some platform features may require a paid subscription.</p>
                  <p className="mt-2">Subscription terms, pricing, and usage limits will be displayed within the platform.</p>
                  <p className="mt-2">Unless otherwise stated:</p>
                  <ul className="mt-2 list-disc space-y-1 pl-6">
                    <li>subscriptions renew automatically</li>
                    <li>users may cancel according to platform billing settings</li>
                  </ul>
                  <p className="mt-2">Fees are non-refundable except where required by law.</p>
                </section>

                <section>
                  <h2 className="text-[26px] font-semibold uppercase tracking-[0.02em] text-[#F74917]">13. Intellectual Property</h2>
                  <p className="mt-3">All platform software, features, design, and technology are owned by TradesStack.</p>
                  <p className="mt-2">Users may not:</p>
                  <ul className="mt-2 list-disc space-y-1 pl-6">
                    <li>copy the platform</li>
                    <li>reverse engineer the software</li>
                    <li>replicate proprietary features</li>
                    <li>build competing services based on TradesStack technology</li>
                  </ul>
                </section>

                <section>
                  <h2 className="text-[26px] font-semibold uppercase tracking-[0.02em] text-[#F74917]">14. Termination</h2>
                  <p className="mt-3">TradesStack may suspend or terminate access if users:</p>
                  <ul className="mt-2 list-disc space-y-1 pl-6">
                    <li>violate these Terms</li>
                    <li>misuse the platform</li>
                    <li>create security risks</li>
                    <li>fail to pay subscription fees</li>
                  </ul>
                  <p className="mt-2">Users may stop using the Service at any time.</p>
                </section>

                <section>
                  <h2 className="text-[26px] font-semibold uppercase tracking-[0.02em] text-[#F74917]">15. Changes to the Service or Terms</h2>
                  <p className="mt-3">TradesStack may update the platform or these Terms periodically.</p>
                  <p className="mt-2">The updated version will include a revised Last Updated date.</p>
                  <p className="mt-2">Continued use of the Service indicates acceptance of the updated Terms.</p>
                </section>

                <section>
                  <h2 className="text-[26px] font-semibold uppercase tracking-[0.02em] text-[#F74917]">16. Governing Law</h2>
                  <p className="mt-3">These Terms are governed by the laws of New Zealand.</p>
                  <p className="mt-2">
                    Any disputes arising from these Terms or the Service will be subject to the jurisdiction of the courts of New Zealand.
                  </p>
                </section>

                <section>
                  <h2 className="text-[26px] font-semibold uppercase tracking-[0.02em] text-[#F74917]">17. Contact</h2>
                  <p className="mt-3">For questions about these Terms:</p>
                  <p className="mt-2">TradesStack</p>
                  <p>Email: hi@tradesstack.com</p>
                  <p>Website: https://tradesstack.com</p>
                </section>
              </div>
            </div>
          </div>
        </section>

        <Footer />
      </main>
    </div>
  );
}
